export const CONFIG = {
  meta: {
    gameTitle: 'SCP Foundation: Site Director',
    version: '0.1.0',
    tickRate: 30,
    autosaveIntervalMs: 30000,
    dayDurationSeconds: 180,
  },

  map: {
    width: 120,
    height: 72,
    tileSize: 24,
    colors: {
      background: '#0b1220',
      gridLine: 'rgba(148, 163, 184, 0.07)',
      wall: '#334155',
      floor: '#1f2937',
      powerOffOverlay: 'rgba(239, 68, 68, 0.18)',
      decontamination: '#0f766e',
    },
  },

  economy: {
    startingBudget: 25000,
    dailyBaseFunding: 6500,
    emergencyReserveThreshold: 4000,
    salaries: {
      guard: 180,
      researcher: 240,
      dClassHandler: 165,
      engineer: 260,
      janitor: 120,
      tacticalResponse: 410,
    },
    constructionCosts: {
      wallSegment: 12,
      corridorTile: 8,
      containmentCellSafe: 500,
      containmentCellEuclid: 900,
      containmentCellKeter: 1600,
      dClassDormitory: 700,
      guardPost: 350,
      researchLab: 1100,
      decontaminationChamber: 900,
      armory: 1300,
      powerGenerator: 1000,
      surveillanceRoom: 1200,
    },
    maintenanceDailyCosts: {
      powerGrid: 220,
      containmentSystems: 300,
      decontaminationSystem: 140,
      surveillanceNetwork: 180,
    },
    recruitCosts: {
      guard: 400,
      researcher: 700,
      engineer: 900,
      janitor: 240,
      dClassTransfer: 110,
    },
  },

  gameplay: {
    staffing: {
      startWithNoPersonnel: true,
      maxApplicantsPerDay: 4,
      hireCooldownSeconds: 8,
    },
    roomRules: {
      preventEditWhenScpInside: true,
      roomEditMessage: 'Modification impossible: un SCP est actuellement présent dans cette salle.',
    },
    contamination: {
      infectionChancePerExposureTick: 0.015,
      severeInfectionThreshold: 0.7,
      decontaminationDurationSeconds: 18,
      dormitoryAccessRequiresDecon: true,
    },
    revolt: {
      baseChancePerHour: 0.01,
      happinessTriggerThreshold: 0.35,
      hungerWeight: 0.25,
      sleepWeight: 0.2,
      fearWeight: 0.35,
      overcrowdingWeight: 0.2,
      armedRiotChanceMultiplier: 2.4,
    },
    hacking: {
      baseHackProgressPerSecond: 1.8,
      chaosInsurgencyBoost: 1.65,
      countermeasureReductionPerEngineer: 0.45,
      maxHackProgress: 100,
    },
    lineOfSight: {
      enableFogOfWar: true,
      guardVisionRangeTiles: 10,
      cameraVisionRangeTiles: 16,
      visionAngleDegrees: 105,
      blinkWindowSeconds: 1.2,
      blinkCooldownSeconds: 7,
    },
    research: {
      intelPerResearcherPerSecond: 0.45,
      breakthroughBonusChance: 0.06,
      unknownScpDiscoveryCost: {
        Safe: 60,
        Euclid: 120,
        Keter: 220,
      },
    },
    tutorial: {
      enabled: true,
      steps: [
        { id: 'buildDorm', text: 'Construisez un dortoir Classe-D.', goal: 1 },
        { id: 'hireStaff', text: 'Recrutez 2 gardes et 1 chercheur.', goal: 3 },
        { id: 'buildContainment', text: 'Construisez une cellule de confinement Safe.', goal: 1 },
        { id: 'generateIntel', text: 'Accumulez 100 points d\'Intel.', goal: 100 },
      ],
    },
  },

  incidents: {
    chaosInsurgency: {
      enabled: true,
      minDaysBeforeFirstAttack: 3,
      attackRollChancePerDay: 0.22,
      hackAttackWeight: 0.42,
      sabotageAttackWeight: 0.33,
      breachAssistWeight: 0.25,
      warningLeadTimeSeconds: 15,
    },
    powerSabotage: {
      blackoutDurationSeconds: 40,
      turretDisableChance: 0.5,
      doorUnlockChance: 0.35,
    },
    decontaminationFailure: {
      chamberBreakChancePerDay: 0.03,
      infectionPulseRadius: 4,
    },
  },

  scpDatabase: [
    {
      id: 'SCP-173',
      codename: 'The Sculpture',
      class: 'Euclid',
      discovered: false,
      containmentCost: 1400,
      danger: 0.87,
      researchDifficulty: 0.72,
      riotInfluence: 0.35,
      hackAttractiveness: 0.65,
      baseMoodImpact: -0.15,
      powers: ['movesWhenUnobserved', 'neckSnap'],
      containmentNeeds: { lightLevelMax: 0.3, minGuardsWatching: 2, reinforcedDoorLevel: 2 },
    },
    {
      id: 'SCP-096',
      codename: 'The Shy One',
      class: 'Euclid',
      discovered: false,
      containmentCost: 1350,
      danger: 0.91,
      researchDifficulty: 0.84,
      riotInfluence: 0.6,
      hackAttractiveness: 0.5,
      baseMoodImpact: -0.22,
      powers: ['rageOnFaceSeen', 'highSpeedCharge'],
      containmentNeeds: { visualContactAllowed: false, soundproofingLevel: 3, reinforcedDoorLevel: 3 },
    },
    {
      id: 'SCP-049',
      codename: 'Plague Doctor',
      class: 'Euclid',
      discovered: false,
      containmentCost: 950,
      danger: 0.63,
      researchDifficulty: 0.68,
      riotInfluence: 0.4,
      hackAttractiveness: 0.4,
      baseMoodImpact: -0.1,
      powers: ['instantLethalTouch', 'createsInfected'],
      containmentNeeds: { biologicalLock: true, medBayNearby: true, reinforcedDoorLevel: 2 },
    },
    {
      id: 'SCP-106',
      codename: 'The Old Man',
      class: 'Keter',
      discovered: false,
      containmentCost: 2100,
      danger: 0.97,
      researchDifficulty: 0.93,
      riotInfluence: 0.75,
      hackAttractiveness: 0.7,
      baseMoodImpact: -0.3,
      powers: ['phasingThroughWalls', 'corrosionTrail', 'pocketDimensionDrag'],
      containmentNeeds: { femurBreakerProtocol: true, antiCorrosionWalls: true, reinforcedDoorLevel: 4 },
    },
    {
      id: 'SCP-682',
      codename: 'Hard-to-Destroy Reptile',
      class: 'Keter',
      discovered: false,
      containmentCost: 3200,
      danger: 1,
      researchDifficulty: 0.99,
      riotInfluence: 0.9,
      hackAttractiveness: 0.85,
      baseMoodImpact: -0.4,
      powers: ['adaptiveRegeneration', 'siegeBreakout', 'massCasualtyRoar'],
      containmentNeeds: { acidBathRequired: true, guardQuota: 8, reinforcedDoorLevel: 5 },
    },
    {
      id: 'SCP-914',
      codename: 'The Clockworks',
      class: 'Safe',
      discovered: false,
      containmentCost: 700,
      danger: 0.25,
      researchDifficulty: 0.52,
      riotInfluence: 0.05,
      hackAttractiveness: 0.2,
      baseMoodImpact: 0.04,
      powers: ['materialRefinement', 'intelBoost'],
      containmentNeeds: { operatorClearance: 2, powerDrain: 'medium', reinforcedDoorLevel: 1 },
    },
    {
      id: 'SCP-999',
      codename: 'The Tickle Monster',
      class: 'Safe',
      discovered: false,
      containmentCost: 500,
      danger: 0.04,
      researchDifficulty: 0.24,
      riotInfluence: -0.2,
      hackAttractiveness: 0.05,
      baseMoodImpact: 0.22,
      powers: ['moraleBoostAura', 'panicReduction'],
      containmentNeeds: { warmEnvironment: true, recreationAccess: true, reinforcedDoorLevel: 1 },
    },
    {
      id: 'SCP-131',
      codename: 'The Eye Pods',
      class: 'Safe',
      discovered: false,
      containmentCost: 420,
      danger: 0.12,
      researchDifficulty: 0.18,
      riotInfluence: -0.05,
      hackAttractiveness: 0.1,
      baseMoodImpact: 0.06,
      powers: ['autoObserve173', 'earlyWarning'],
      containmentNeeds: { freeRoamAllowed: true, minPlayAreaTiles: 8, reinforcedDoorLevel: 1 },
    },
    {
      id: 'SCP-079',
      codename: 'Old AI',
      class: 'Euclid',
      discovered: false,
      containmentCost: 1200,
      danger: 0.7,
      researchDifficulty: 0.78,
      riotInfluence: 0.25,
      hackAttractiveness: 0.95,
      baseMoodImpact: -0.08,
      powers: ['networkIntrusion', 'doorControlHijack'],
      containmentNeeds: { isolatedNetwork: true, offlineBackup: true, reinforcedDoorLevel: 2 },
    },
    {
      id: 'SCP-939',
      codename: 'With Many Voices',
      class: 'Keter',
      discovered: false,
      containmentCost: 1900,
      danger: 0.89,
      researchDifficulty: 0.86,
      riotInfluence: 0.58,
      hackAttractiveness: 0.3,
      baseMoodImpact: -0.19,
      powers: ['voiceMimicryLure', 'packHunt'],
      containmentNeeds: { acousticDampening: true, thermalScanners: true, reinforcedDoorLevel: 4 },
    },
    {
      id: 'SCP-093',
      codename: 'Red Sea Object',
      class: 'Euclid',
      discovered: false,
      containmentCost: 1000,
      danger: 0.66,
      researchDifficulty: 0.8,
      riotInfluence: 0.32,
      hackAttractiveness: 0.45,
      baseMoodImpact: -0.05,
      powers: ['mirrorTeleport', 'dimensionalLeak'],
      containmentNeeds: { mirrorChamber: true, biometricLock: true, reinforcedDoorLevel: 3 },
    },
    {
      id: 'SCP-035',
      codename: 'Possessive Mask',
      class: 'Keter',
      discovered: false,
      containmentCost: 1700,
      danger: 0.9,
      researchDifficulty: 0.88,
      riotInfluence: 0.67,
      hackAttractiveness: 0.4,
      baseMoodImpact: -0.17,
      powers: ['mindControl', 'acidicSecretion'],
      containmentNeeds: { antiPossessionProtocol: true, autoTurretCoverage: true, reinforcedDoorLevel: 4 },
    },
    {
      id: 'SCP-053',
      codename: 'Young Girl',
      class: 'Euclid',
      discovered: false,
      containmentCost: 850,
      danger: 0.58,
      researchDifficulty: 0.64,
      riotInfluence: 0.4,
      hackAttractiveness: 0.2,
      baseMoodImpact: -0.1,
      powers: ['aggressionAura', 'rapidRegeneration'],
      containmentNeeds: { noDirectContact: true, controlledPlayArea: true, reinforcedDoorLevel: 2 },
    },
    {
      id: 'SCP-500',
      codename: 'Panacea',
      class: 'Safe',
      discovered: false,
      containmentCost: 600,
      danger: 0.06,
      researchDifficulty: 0.45,
      riotInfluence: -0.06,
      hackAttractiveness: 0.12,
      baseMoodImpact: 0.08,
      powers: ['curesInfection', 'medicalSupplyBoost'],
      containmentNeeds: { medStorage: true, accessClearance: 3, reinforcedDoorLevel: 1 },
    },
    {
      id: 'SCP-012',
      codename: 'A Bad Composition',
      class: 'Euclid',
      discovered: false,
      containmentCost: 720,
      danger: 0.51,
      researchDifficulty: 0.57,
      riotInfluence: 0.22,
      hackAttractiveness: 0.08,
      baseMoodImpact: -0.07,
      powers: ['compulsionEffect', 'bleedDamageOverTime'],
      containmentNeeds: { isolationGlass: true, noAudioContact: true, reinforcedDoorLevel: 2 },
    },
    {
      id: 'SCP-2006',
      codename: 'Too Spooky',
      class: 'Safe',
      discovered: false,
      containmentCost: 640,
      danger: 0.18,
      researchDifficulty: 0.33,
      riotInfluence: 0.11,
      hackAttractiveness: 0.1,
      baseMoodImpact: -0.02,
      powers: ['fearSpike', 'shapeShiftingPrank'],
      containmentNeeds: { entertainmentFeed: true, minSocialExposure: 2, reinforcedDoorLevel: 1 },
    },
    {
      id: 'SCP-1048',
      codename: 'Builder Bear',
      class: 'Keter',
      discovered: false,
      containmentCost: 1500,
      danger: 0.82,
      researchDifficulty: 0.8,
      riotInfluence: 0.47,
      hackAttractiveness: 0.28,
      baseMoodImpact: -0.09,
      powers: ['constructHostileReplicas', 'stealthEscape'],
      containmentNeeds: { toyMaterialBan: true, acousticSensors: true, reinforcedDoorLevel: 3 },
    },
    {
      id: 'SCP-1313',
      codename: 'Constructive Criticism',
      class: 'Safe',
      discovered: false,
      containmentCost: 480,
      danger: 0.09,
      researchDifficulty: 0.27,
      riotInfluence: -0.02,
      hackAttractiveness: 0.06,
      baseMoodImpact: 0.03,
      powers: ['productivityHint', 'minorIntelBoost'],
      containmentNeeds: { writingMaterials: true, weeklyInterview: true, reinforcedDoorLevel: 1 },
    },
    {
      id: 'SCP-2317',
      codename: 'A Door to Another World',
      class: 'Keter',
      discovered: false,
      containmentCost: 2600,
      danger: 0.96,
      researchDifficulty: 0.92,
      riotInfluence: 0.7,
      hackAttractiveness: 0.55,
      baseMoodImpact: -0.28,
      powers: ['ritualContainment', 'cataclysmCountdown'],
      containmentNeeds: { ritualTeamRequired: true, chainIntegrityMin: 0.95, reinforcedDoorLevel: 5 },
    },
    {
      id: 'SCP-3008',
      codename: 'A Perfectly Normal IKEA',
      class: 'Euclid',
      discovered: false,
      containmentCost: 1250,
      danger: 0.69,
      researchDifficulty: 0.73,
      riotInfluence: 0.31,
      hackAttractiveness: 0.26,
      baseMoodImpact: -0.04,
      powers: ['interiorPocketDimension', 'staffEntitySpawn'],
      containmentNeeds: { anchorBeacons: 4, navigationTeam: true, reinforcedDoorLevel: 3 },
    },
  ],
};

export default CONFIG;
